[program:wms-worker]
process_name=%(program_name)s_%(process_num)02d
# Sesuaikan path di bawah dengan path absolut proyek Laravel Anda
command=php /var/www/heavytrack-wms/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --timeout=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
# Gunakan user web server (biasanya www-data di Ubuntu/Debian)
user=www-data
numprocs=4
redirect_stderr=true
# Lokasi file log worker
stdout_logfile=/var/www/heavytrack-wms/storage/logs/worker.log
stopwaitsecs=3600
